export const EXPERIENCES = [
	{
		id: "hire-me",
		company: "to-your-company",
		period: "available immediately",
		role: "Hire me :)",
		location: "Office/Hybrid/Remote",
		logo: "/placeholder.svg?height=80&width=80",
		color: "green",
		duties: ["Ready to work for you"],
		technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "GraphQL"],
	},
	{
		id: "jemWszkole",
		company: "jemWszkole.pl",
		period: "02.2025 - 03.2025",
		role: "React Developer",
		location: "Katowice, Poland",
		logo: "/placeholder.svg?height=80&width=80",
		color: "blue",
		duties: [
			"Collaborating with the team to prepare web applications for publication",
			"Identifying, troubleshooting, and fixing bugs in web applications",
			"Continuously improving the quality of the codebase by refactoring and optimizing",
			"Implementing new interfaces and functionalities to enhance user experience",
		],
		technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "GraphQL"],
	},
	{
		id: "gainflow",
		company: "Gainflow",
		period: "12.2024 - present",
		role: "Co-founder & Software Developer",
		location: "Remote",
		logo: "/placeholder.svg?height=80&width=80",
		color: "purple",
		duties: [
			"Implemented new features and functionalities based on user feedback",
			"Optimized app performance and collaborated with backend developers",
			"Conducted market research and analyzed user needs",
			"Brainstormed and conceptualized innovative functionalities",
			"Prioritized features based on impact and feasibility",
			"Contributed to the development of brand vision, mission, and values",
		],
		technologies: ["React Native", "TypeScript", "Redux", "Node.js", "Firebase"],
	},
	{
		id: "hexocean",
		company: "HexOcean",
		period: "2021 - 2024",
		role: "Frontend Developer",
		location: "Warsaw, Poland",
		logo: "/placeholder.svg?height=80&width=80",
		color: "indigo",
		duties: [
			"Created new components with styles and unit tests",
			"Created email templates in HTML",
			"Implemented new features and created business logic",
			"Conducted code reviews and performed refactoring",
			"Fixed issues reported by the QA team",
			"Directly contacted clients, agreed on business requirements",
			"Clarified requirements for new features to maintain project consistency",
			"Managed the development team and provided new features",
		],
		technologies: ["React", "TypeScript", "Redux", "Styled Components", "Jest", "Testing Library"],
	},
];
